import Foundation

/// SF Symbol names mapped from the design's custom stroke icons (`theme.jsx`).
enum Sym {
    static let homeOutline = "house"
    static let homeFill = "house.fill"
    static let chart = "chart.bar"
    static let target = "target"
    static let pulse = "waveform.path.ecg"
    static let gear = "gearshape"
    static let gearFill = "gearshape.fill"
    static let plus = "plus"
    static let chevron = "chevron.right"
    static let chevronL = "chevron.left"
    static let chevronD = "chevron.down"
    static let check = "checkmark"
    static let bell = "bell.fill"
    static let moon = "moon.fill"
    static let clock = "clock"
    static let flame = "flame.fill"
    static let arrowUp = "arrow.up"
    static let arrowDown = "arrow.down"
    static let wallet = "creditcard.fill"
    static let calendar = "calendar"
    static let watch = "applewatch"
    static let widget = "square.grid.2x2.fill"
    static let sparkle = "sparkles"
    static let dollar = "dollarsign.circle.fill"
    static let trophy = "trophy.fill"
    static let dots = "ellipsis"
    static let xmark = "xmark"
    static let share = "square.and.arrow.up"
    static let eye = "eye"
    static let cursor = "cursorarrow"
    static let pie = "chart.pie"
    static let mega = "megaphone"
    static let coin = "centsign.circle"
    static let globe = "globe"
    static let layers = "square.stack.3d.up.fill"
    static let apps = "square.grid.2x2"
}
